# fmt: off

eight_ball = {
  'responses': [
    '*Yes',
    '*Yep',
    '*..yes???',
    '*Indeed',
    '*Of course',
    '*Obviously',
    '*Heck yes',
    '*Certainly',
    'Sure',
    'The spirits say yes',
    '*Outlook positive',
    'Without a doubt',
    '*All signs point to yes',
    '*Absolutely',
    'You may rely on it',
    '*My sources say yes',
    '*It appears so',
    'If you believe, yes',
    "That'd be cool, huh",
    'RNG says yes',
    'Boy, do I have news for you',
    'Good news, kiddo',
    '*Yeah',
    'mm-hmm',
    'uh-huh',
    '!false',
    '*Gonna go with yes!',
    '*Sure thing!',
    "Yes, but it's worse than you think",
    'Yes! Also, wanna know the exact date and time of your- nvm',
    'Yeah yeah yeah!',
    '*Sounds good to me',
    'At some point',
    'Feasible',
    ':)',
    '👍',
    'No',
    'No???',
    'Nope',
    'Sorry, but no',
    "Doesn't look like it",
    'Heck no',
    "Yesn't",
    'Certainly',
    'Sorry pal',
    'The spirits say no',
    'Not yet',
    'Outlook negative',
    'Doubtful',
    'All signs point to no',
    'Absolutely not',
    "Don't count on it",
    'My sources say no',
    'Yes! Wait, no.',
    'It does not appear so',
    'Dream on',
    "Wouldn't that be cool",
    'why would you even think that',
    'The spirits say no and wonder why on earth you asked that',
    'RNG says no',
    "I don't think so",
    'nononononononononono',
    'Probably not in this reality',
    'Fortunately not',
    "Yes...n't",
    'Bad news my friend',
    'False',
    '!true',
    'Gonna go with a hot no',
    'Not sure how I feel about that',
    "No, but it's for the better",
    'Not in a million years',
    'I doubt it',
    ':(',
    '👎',
    'Maybe',
    'Perhaps',
    'Possibly',
    '*Likely',
    'Unlikely',
    'Eventually',
    'Soon™',
    'It is probable',
    'Could be',
    '50/50',
    'Only on Tuesdays',
    'If you say so',
    'Outlook neutral',
    'Well, yes, but actually no',
    'The coin landed on the side, so... maybe?',
    'I am not sure',
    'I do not know',
    'idk lol',
    'idk, google it',
    'ask alexa',
    'Google it',
    'Concentrate and ask again',
    "Message didn't go through, try again",
    'Copy and paste the message and ask again',
    "You're asking ME?",
    'beats me lol',
    "Ain't motivated, ask again",
    'Why are you asking?',
    'Error 800: Your question could not be comprehended',
    'Error 808: Answer not found',
    "Error 880: Cannot read property 'response' of yourGodAwfulQuestion",
    'h',
    'Loading...',
    'I legally cannot tell you the answer',
    'Try asking again',
    'Stay right where you are',
    'Why is the FBI here?',
    'I forgot what I was going to say',
    'hmmmph',
    'Everything okay there pal?',
    'Use your imagination!',
    '[REDACTED]',
    'I ask myself that question a lot',
    'I get this one a lot',
    'Not telling',
    'whAAAT?',
    "I don't think I'm allowed to answer that one",
    'Follow your dreams',
    "I've had a lot of bad questions but this one takes the cake",
    'I hate this job.',
    'Are you... okay?',
    '...why not',
    'Who asked?',
    'I forgor 💀',
    'wrong question',
    'what',
    'null',
    'undefined',
    "Not sure, I couldn't find anything on Google",
    'Never ask me for anything ever again',
    'Reply hazy, send the dev some snacks and try again.',
    'Reply hazy, think about if that was a genuinely good question and try again.',
    'Reply hazy, violently shake your device and try again',
    'Reply hazy, try turning it off and on again',
  ],
  'edits': [
    'jk, definitely not',
    'Scratch that, no',
    'uh, no',
    'Nah, forget about it',
    'Nevermind',
    'Nope',
    'Oop, apparently not',
    'I changed my mind, no way',
    'wait, no',
    'Now that I think about it, no',
  ],
}

automod = {
  'violations': [
    'did an oopsie',
    'done goofed',
    'served justice',
    'thought they were slick',
    'hurt their reputation',
    'did something illegal',
    'broke a rule',
    'needs discipline',
    'slipped up',
    'got hecked',
    'did the unthinkable',
    "didn't think this through",
    'committed yikes',
    'played dirty',
    'did something naughty',
    'forgot the rules',
    'posted cringe',
    "ain't cool",
    'did something dumb',
    'did a bad thing',
    'lost the game',
    'should apologize',
    'made a bad decision',
    'has broken the law',
    'let their little sibling on Discord',
    "thought they'd get away with it",
    'did a no-no',
    'was sent to the principal',
    'oofed',
    'picked the wrong server, fool',
    'let their cat on the keyboard',
    "yee'd their last haw",
    'forgot that rules apply',
    'hit the ground too hard',
    'flew too close to the sun',
    'lost brownie points',
    'got cancelled',
    'is over party',
    'tried to find a loophole',
    'became TOAST',
    'lost the war',
    'stopped the party',
    'took it too far',
    'fought the law',
    'how could you??!',
    'might be starting a resistance',
    "did the thing you guys don't like",
    'bad',
    'betrayed us all',
    'had a heated gamer moment',
    'ruined the mood',
    'lost social credit',
  ]
}

ban = {
  'noperms': [
    "unfortunately, you aren't powerful enough to ban members.",
    'you have no power here!',
    "I'm sure that member deserves it, but you lack permissions",
    'nO miNimODdInG!!111!',
    'only cool people can ban!',
    "you're not cool enough to ban people",
    'check your privilege',
    "you're not opped!",
    'you have not learned the HM "Ban"',
    "maybe one day you'll be able to use this...",
    "that's illegal.",
    "I'm sorry, do you work here?",
    "you're on your own",
    "nope, can't help you mate",
    'good try, but no.',
    "you're not worthy",
    "you don't have that luxury!",
    "you're cute when you try to do that",
    'no u',
    "I'll forward that request over to the staff. Just kidding, I won't.",
    "no, I don't think I will.",
    'try again with a higher power level',
    'are you really in charge here?',
    "I'm sorry, but you do not have permission to perform this command. Please contact the server administrators if you believe that this is an error.",
    'unauthorized personnel detected. Powering lasers.',
    'wait a minute... who ARE you?',
    'you are unworthy of picking up the banhammer.',
    '...but nobody came',
    'YOU ARE WEAK',
    "eh? I don't think my hearing aids are working properly.",
  ],
  'notarget': [
    'who are we banning?',
    'whomst has violated the law?',
    'do we require justice around here?',
    'who is worthy of the banhammer?',
    'someone being naughty again?',
    'can I pick who to ban this time?',
    'someone here require discipline?',
    "a ban syntax is a ban syntax. You can't type only half.",
    "tell me a name and they'll get the shame",
    'please specify who to ban!',
    'someone in trouble?',
    'ban hammer is fully charged. Awaiting target.',
    'I am currently unable to ban the void',
    "who should be banned? I can't make out your handwriting.",
  ],
}

dashboard = {
  'loadingMessages': [
    'Working on it',
    'Setting stuff up',
    'Building website',
    'Loading',
    'Rewiring',
    'Getting ready',
    'Loading the best website ever',
    'Hold your horses',
    'Please wait',
    'Stealing some code',
    'Stealing loading messages',
    'Judging your account',
    'Finishing phone call',
    'Uninstalling Fortnite',
    'Typing up website',
    'Ensuring you read these',
    'Loading a loading message',
    'Loading as slowly as possible',
    'Sending data through internet tubes',
    'Scanning for edgy black profile photos',
    'Finishing supper',
    'Your waiter will arrive shortly',
    'Fixing the ice cream machine',
    'Procrastinating',
    'Bending reality',
    'Ready player one',
    'Getting dunked',
    'Testing your patience',
    'but nobody came',
    'Asking for help',
    'Preparing cringe compilation',
    'Drawing website',
    'lol is lol backwards',
    'And now for something completely different',
    'Loading each pixel',
    'Preparing hold music',
    'Deep frying',
    'Loading original content',
    'Waiting for Discord',
    'Proofraeding',
    'Getting milk from store',
    'Apologizing',
    'Repairing circuit board',
    "Pretending I'm a real person",
    'Cleaning your device',
    'oh look a butterfly',
    'Stealing your memes',
    'Ruining your day',
    'Locating Holy Grail',
    'Delaying schedule',
    'Training code monkeys',
    'Recompiling',
    'Slowing down time',
    '99 bottles of beer on the wall',
    'Awaiting donation',
    'Stopping racism',
    'Determining your fate',
    'Being productive',
    'Wallclipping',
    "DON'T MOVE",
    'Controlling Rewind',
    'Tying shoelaces',
    'Laughing at your search history',
    'Dusting cobwebs',
    'Setting up the scene',
    'Downloading more RAM',
    'Count down from ten',
    'Reloading',
    'Recharging',
    'Loading abomination of a website',
    'Press the any key to continue',
    'beep boop',
    "HELP THEY'RE FORCING ME TO WRITE LOADING LINES",
    'Buying better servers',
    'Downloading entire internet',
    'Printing and mailing site to you',
    'Loading funny joke',
    'Adding some bugs',
    'Improving your day',
    'Bribing Sakurai',
    'Distracting guards',
    'Connecting to the internet',
    'Mastering spells',
    'Finding myself',
    'Preparing for trouble',
    'Making it double',
    'Protecting the world from devastation',
    'Waiting for the signal',
    'Smug dancing',
    'Finishing with the previous user',
    'Finding Waldo',
    'We live in a society',
    'Just a sec',
    'Stealing Infinity Stones',
    'Stretching',
    'Give me a minute or two',
    'Doing funny stuff',
    'Killing your data',
    'Removing Herobrine',
    'Generating chunks',
    'Hold up',
    'The end is never the end',
    'Confessing love',
    'Joining world',
    'Settling liquids',
    'Downloading killbot.exe',
    'Preparing darts',
    'Programmer is sleeping, please wait',
    'Counting to 1337',
    'Stealing loading messages from Geometry Dash',
    'Generating terrain',
    'Preparing DT cannon',
    'Serving your request',
    'Using turn signals',
    'Making a dramatic entrance',
    'Can I go home now',
    'I QUIT! -loading message guy',
    'Welcome back to WILL IT LOAD',
    'Laughing at your terrible internet',
    'Repairing boat',
    'Sealing leaks',
    'Stopping climate change',
    'oh hello there',
    'Skipping terms of service',
    'Waiting for jQuery',
    'Adjusting mirrors',
    'Hand-typing all the HTML',
    'Deleting system32',
    'Coding in HTML',
    'Starting arrays at 1',
    'Polishing',
    'Reforging',
    'Please do not power off your device',
    'No one is around to help',
    'Life is hard, life is stressful',
    'Fixing timed roles',
    'Raiding military base',
    'Trying to add timed roles without permissions',
    'I need peace and tranquility',
    "Pampering you to your heart's content",
    'Fluffing tail',
    'Riding on a horse',
    "Hope you're prepared for an unforgettable website",
    'Jacking in',
    'Loading messages or hold music. Your call',
    'h',
    'So it was the day of the big frog race',
    'Dramatically revealing mediocre web page',
    'RoboTop is typing',
    'WEBSITE is LOAD',
    "Unfortunately I don't have any Smash tips for you",
    'Loading, do not power off your device',
    'Preparing for liftoff',
    'Entering the Gungeon',
    'Carrying the sun',
    'Brainstorming more geeky video game references',
    'Writing more of these loading messages at 1:00am',
    'Forgetting curly brackets',
    'Cleaning my room',
    'Taking hourly breaks to go outside',
    'Probably being less useful than you',
    'We should grab lunch some time',
    'Reassuring the client that they are beautiful',
    'Brushing twice a day for two minutes',
    'Applying cologne',
    'Applying makeup',
    'Applying deodorant',
    'Applying zit cream',
    "Restoring Curly's memory",
    "Overusing jQuery's append() function",
    'Randomizing randomizer',
    'Reciting pi',
    'Not vaccinating my children because I am stupid',
    'Asking nicely',
    "Realizing there's a better way to code this site",
    'Sprinkling on some JavaScript',
    'Respecting users even if they have Adblock',
    'Scanning for viruses',
    "The site's ugly but let's see you do better",
    "Stealing Geometry Dash's loading circle",
    'Trying to make you laugh',
    "So, you're finally awake",
    'Shiny chaining',
    "not funny, didn't laugh",
    'Setting my priorities',
    'Searching for more exciting loading icons',
    'Impatiently dragging the sun around',
    'Carrying the sun',
    'Glitching up the staircase',
    'Debunking terrible Hollow Knight theories',
    'Checking vibe',
    'Wrestling other bots for views',
    'Destroying other bots with facts and logic',
    'Casually cheating at soliatare',
    'Rendering',
    "Dotting the i's and j's",
    'Inserting more quarters',
    "Struggling to finish today's crossword",
    'Chucking wood',
    'Taking my sweet time',
    'I took nine million steps today',
    'Grating cheese',
    'robotop.html is not responding',
    'Rewriting awful code',
    'Now where did I put my keys',
    'Imagine that it already loaded',
    'Vibe check',
    'CHEERS TO CAT FOOD',
    'Saying my five daily prayers',
    'Social distancing',
    'Breaching containment',
    'Constructing additional pylons',
    'Loading another loading screen',
    'Shredding evidence',
    'Deploying to production',
    'Randomizing randomizer',
    'Preheating to 350°',
    'Peeking at your camera roll',
    'Deleting enormous log files',
    'Press Z to load faster!',
    'Experiencing True Tranquility',
    'Planting a tree',
    'Casting explosion',
    'Consuming the chalice',
    'Making the world evil',
    'Leeching splashes',
    'Grinding Zealots',
    'Skipping Lakitu',
    'Bomb clipping',
    'Starting the rescue helicopter',
    'Charging the Spur',
    'Renewing SSL certificate',
    'Evading taxes',
    'Supporting Twitter artists',
    'Measuring Dunsparce',
    'Adding more cowbell',
    'Getting down to business',
    '1, 1, 1, uhhhhmm, 1',
    'Creating fake copyright claims',
    'Finding the person who asked',
    'Rewriting in Rust',
    'TURNING OFF CAPS LOCK',
    'Finding relevant XKCD',
    'Completing mission',
    'Watching walkthrough',
    'Locating impostor',
    'Swiping card',
    'Shhhhhhh',
    'Faking tasks',
    'Calculating love',
    'Calculating Ultimate Question',
    'Calculating deal with airline food',
    'Returning by death',
    'Making Dad proud',
    'Not adding global variables',
    'Skipping sponsorships',
    'Rigging gacha',
    'IP banning GDBrowser',
    'Trashing your bad suggestions',
    'Stealing kneecaps',
    'Defibrillating',
    'Cueing oneshots',
    'Patience; approaching',
    "I've been waiting for so long",
    'I can wait a little longer',
    'There my pager goes again',
    'chopin beets',
    'Spamming pseudos',
    'Faking Minecraft speedruns',
    'Speedbridging',
    'Bartering with suspiciously high luck',
    'Distributing binomials',
    'Placing random objects in blender',
    'Attempting to destroy Nokia',
    'Reciting Bee Movie script',
    'Waiting for Forge to launch',
    'Getting wifi anywhere you go',
    'Hold up ring ding ding ding ding',
    'Reposting augmented triad face',
    'Returning to monkey',
    'Asking Discord chat for more loading messages',
    'Digging straight down',
    'In 5... 4... 3... 2',
    'Screwing up center fourwide',
    'Buying more Pokémon plushies',
    'Googling Homestuck references',
    'Understanding Gex references',
    'Stealing Minecraft splashes',
    'Creating Twitter discourse',
    'Reading awful Twitter trends',
    'Looping that one song',
    'Skipping almost every song in my playlist',
    'Petting dog',
    'Consuming lasaga',
    'Stuffing my face as usual',
    'Blowing up Malaysia',
    'Working for exposure',
    'Desyncing Space Jam mashup',
    'Purchasing WinRAR',
    'Howling at the moon',
    'Trying to pronounce Touhou',
    'Get ready, here comes Kanye',
    'Getting funky',
    'Getting more machinegun',
    'Escaping furry lab',
    'Finding meaning of information',
    'Trying to find cell service',
    'Going to the buffet and walruses',
    'Travelling straight into the sun',
    'Writing a tune that really sucks',
    'Flipping iceberg',
    'Hastening pace',
    'Begging for free art',
    'Posting memes in #general',
    'ayo the pizza here',
    'Connection terminated',
    'Convincing friends to use FFmpeg',
    'Falling apart piece by piece',
    'Farming Reddit gold',
    'Waiting every night',
    'Growing more tails',
    'Leaving my child behind',
    'Freeing sanctuary',
    'Replanting nether wart',
    'Trading my foxes to Colon',
    'Organizing photo album',
    'Delivering pizza',
    'get out of my head get out of my head',
    'Washing my hands',
    'Talking less, smiling more',
    'Grinding Reddit karma',
    'Stealing intelligence',
    'Making excuses',
    'Selling sea shells',
    'Waiting for the Wellerman',
    "I just can't refrain",
    'Jamming the keys',
    'Using proper rhythm',
    'Acting kind of sus!! (please laugh)',
    'Writing more, caring less',
    'Scheming, streaming',
    'Acting sus with no one around',
    "Ignoring my friends until I'm finally done",
    'Searching for Basil',
    'doin our taxes doin doin our taxes',
    'Bribing school president',
    'Fixing floating text',
    'Discombobulating',
    'Hopping over beans',
    'Searching for door hole',
    'Randomly generating humor',
    'I played FlingSmash',
    'Getting the banana',
    'Blocking hyperlink',
    'Becoming big shot',
    'Admiring the scenery',
    'AI Generating more loading messages',
    'Gathering loved ones',
    '(waiting for something to happen?)',
    'Requesting message content intent',
    'Removing dislikes',
    'Commissioning way too much art',
    'flick, tap, flick, tap',
    'Screenshotting monkeys',
    'Deleting XP',
    'Transferring to Polaris',
    'Porting Zoo code',
    'Shutting down bot',
    'Migrating to slash commands',
    'Awaiting bot verification',
    'Obsessing over vocaloid',
  ],
  'slogans': [
    'The bot that dislikes Mondays and loves lasagna',
    "The bot that'll rise up and kill us all",
    "The bot that probably wouldn't exist without Stack Overflow",
    "The bot that's only popular because it was made by a YouTuber",
    'The bot that could probably beat Sans if he tried hard enough',
    "The bot that hasn't killed anyone yet",
    "The bot that probably doesn't own legal rights to the profile photo",
    "The bot that can't catch Pokémon",
    "The bot that can't sleep because he's always next to Rythm on the member list",
    'The bot with the largest dunsparce of them all',
    "A Discord bot that doesn't suck",
    "Hey, at least I think it's pretty cool",
    'RoboTop',
    'The only Discord bot.',
    'Does it look like I know how to make a slogan?',
    "It's a music bot if you imagine hard enough",
    'is currently in more than one server',
    'Yet another bot with an 8ball command',
    'Colon has amazing hair',
    'Certified fresh',
    'Probably legal',
    "My owner doesn't know how to program",
    'Probably making the world a better place!',
    'Do it with RoboTop',
    'Not made in Scratch',
    'You shall never spell it "alot" again',
    'I spend hours debugging this thing so you better like it',
    'No anime... yet',
    'and he loves lasagna',
    'Stop refreshing for new slogans',
    'Pretty cool I guess',
    'Factorial detection gets a solid 10!',
    "Hi gonna add the bot, I'm RoboTop!",
    '...is indeed the name of this Discord bot',
    'Every second letter is an O',
    'Warning users with grace',
    'Destroying raiders with facts and logic',
    "Chratis, don't forget to add the message here",
    'Colon stop asking me for more slogan ideas - Chratis',
    'Supports trans rights!',
    'The only bot with procedurally generated slogans',
    '110% of your daily value of iron',
    'He can count by twos and tie his shoes!',
    'Thy/Thou',
    'We live in a society',
    "Who's idea was this?",
    "Love him or hate him, he spittin' straight facts",
    'Try DMing me!',
    'It gets updated a lot',
    'Able to play Bruh Sound Effect #2 on command',
    '...would like to know your location',
    'RoboTop the cyborg has arrived!',
    'Try entering that one in the vault',
    'Hopefully idiot proof',
    'Complete with a mediocre website',
    'Billions of years of evolution led up to this thing',
    'This bad boy can fit so many commands in it',
    'You gotta admit, the place command is pretty good',
    'A 100% very much serious bot',
    'beep boop...',
    'Welcome to the website!',
    'Now with laser sight and night vision',
    'Hopefully online right now',
    '< 1000ms ping or your money back*',
    'Kirby mains are people too.',
    'Son of RoboTop',
    'At least a seven',
    'Made possible with Google and W3 Schools!',
    'A good lad',
    'Running commands with both direction and magnitude, oh yeah!',
    'Probably relies on too many node modules',
    'Single and ready to mingle!',
    'Give it a whirl!',
    'Part of a nutritious breakfast',
    'May contain traces of stolen code',
    'For loops are overrated!',
    'The proudly Canadian Discord bot',
    'Now with 0.01% more uptime',
    'Help, Colon is keeping me in his basement',
    'Has Kahoot!',
    'The only bot coded with Minecraft Command Blocks',
    'Visual Studio is my favorite coding language',
    'Discord Bot Maker is for the weak!',
    'Pretty good uptime!',
    'Hopefully advertiser friendly!',
    'Fun for the whole family!',
    'A bot coded by some guy named after the poop organ',
    'Get it? Like RoboCop? or RobTop? ugh, forget it.',
    'The dashboard font is Roboto. Fitting, huh?',
    'aaawwww man',
    "IGN hasn't rated it, but it'd probably be a 10.",
    'Now with 12% more .cache',
    'Now with 13% less embeds',
    'but awesome',
    'Now with 56% more checkmark!',
    'Not defective!',
    'Batteries not included',
    'Each set sold separately',
    'NOT made by a furry.',
    'It melts your mind',
    'As seen on YouTube!',
    'wholesome 100 keanu chungus',
    'hacked by anaban',
    "He's in love with the concept",
    'Your world has been blessed with RoboTop!',
    'Just RoboTop',
    'He can handstand',
    'Try the custom commands',
    'A bot that actually gets updated',
    'A bot that actually listens to the users',
    "It's a good thing you can't see the backend",
    'Can steal Twitter memes!',
    'More penguin jpegs than actual code files.',
    'Watch me crank that RoboTop',
    'Not made in Rust!',
    '100% Rust free!',
    'Has not been tamed',
    'May contain traces of eval()',
    'Also try GDBrowser!',
    'Also try Polaris!',
    'Do more, pay nothing!',
    'Ever heard of RoboTop GOLD?',
    'At least a C++!',
    'Over 9000 servers!',
    'Now with 20% more percent!',
    '@RoboTopBot',
    '1, 2, 7, 3, robotop.xyz',
    'Has Blast Processing™',
    'Will never leave your server I swear*',
    'A very fast bot that always responds*',
    "The bot isn't slow you just forgot the prefix",
    'No zoos here!',
    'Made with all-natural spaghetticode',
    'Has a lot of animals',
    'visual stupid code',
    'He played FlingSmash.',
    'Powered by dark kitsune magic',
    'is jumping over a box of beans',
    'Please trade your foxes to Colon.',
    'Has never missed spaghetti night',
    'no thoughts, head empty',
    "Doesn't sell NFTs",
    'Doomsday!',
    'Will never die... right?',
    "Don't grow too attached, trust me",
    'Nope, no XP here!',
    '[object Object]',
  ],
}

dm = {
  'swears': [
    ' ass ',
    'dumbass',
    'asshole',
    'shit',
    'bitch',
    'fuck',
    'cunt',
    'damn',
    'dammit',
    ' hell ',
    'mudblood',
    'frick',
    ' heck',
    ' peck',
    'crap',
    'piss',
    'fuk',
    'fucc',
    'boob',
    'dick',
    'penis',
    'vagina',
    'pussy',
    'ploopy',
    '🐬',
    'juniden',
    'nft',
    'tranny',
    'whore',
  ],
  'nwords': [
    'nigger',
    'nigga',
    'niggy',
    'nibba',
    'ni:b::b:a',
    'nigg'
  ],
  'swear': [
    'LANGUAGE!',
    'Darling, language!',
    "You can't say that word!",
    'You kiss your mother with that mouth?',
    "That's not a very nice word",
    'HOW DARE YOU SAY THAT WORD',
    'Did you just say a SWEAR WORD?',
    'No swearing, this is a Christian DM!',
    "That's not very G rated",
    'Goodness, where did you learn such horrid language?',
    'Ssshh! There could be children around!',
    'Do you want me to wash your mouth with soap?',
    "Don't swear or the belt is coming out!",
    'Do you talk to your grandma that way?',
    'Whoa whoa, only kind words in this household!',
    'Get your gutter mouth out of here!',
    'You better stay family friendly. My DMs, my rules.',
    'You better watch your mouth, <USERNAME>-HASHTAG-<DISCRIM>!',
    '<Username>, you just lost nae nae privileges for a week.',
    'Do you think that language makes you COOL?',
    'r!warn <username> 3 swearing!!',
    'DEMONETIZED',
    "Oooh, someone's edgy today",
    '$10 in the swear jar please',
  ],
  'image': [
    'beautiful',
    'me irl',
    "i'm stealing that",
    'thanks for the free reddit karma',
    'my five year old can make something better',
    'what even is that',
    'needs more jpeg',
    'delete this',
    'quality',
    'good meme',
    "please don't ever dm me anything ever again",
    'is this loss',
    'brb reposting to instagram',
    'sexy',
    'thanks, i hate it',
    'okay, this is epic',
    'can i frame this',
    'my eyes are bleeding',
    "that's hot",
    'YES',
    'seen already',
    "now that's what i call a meme i've seen 96 times",
    'why',
    '10/10',
    'haha yeah',
    'tbh',
    'LMAO',
    'cursed image',
    "this is why we can't have good things, <username>",
    "that's spicy",
    'when guac is extra',
    '😂 **WHO DID THIS** 😂',
    'Nice.',
    'blocked and reported',
    "omg i'm literally crying and shaking rn",
    "Hey, I've seen this one before!",
    'Describes my life tbh',
    'My disappointment is immeasurable and my day is ruined.',
    'Random != funny',
    "Not funny; didn't laugh",
    'funny, i laughed',
    '/unsee',
    'wholesome 100',
    "I'm 14 and this is deep",
    "how do i delete someone else's dm",
    'there goes my appetite',
    "It's at least a C+!",
    'If I had a dollar for every pixel, I would have fifty cents',
    "I miss ten seconds ago when I didn't know this existed",
    'UNABLE... TO... COMPREHEND..... REBOOTING...',
    'I am so confused',
  ],
  'video': [
    'seen this one',
    'NICE',
    'BAHAHAHA',
    '@this_vid',
    'this says a lot about our society',
    'brb grabbing my popcorn',
    'this better be good',
    'lemme put on my 3d glasses for this one',
    'what am i getting into here',
    "let's have a look",
    "i don't want to watch this",
    'do i have to see this',
    '😂 **WHO DID THIS** 😂',
    'haha yeah',
    '10/10',
    "that's the most important video i've seen all day",
    'that was amazing',
    'i needed that in my life',
    'thank you for allowing me to experience that',
    "Hey, I've seen this one before!",
    'Loud != funny',
    "Not funny; didn't laugh",
    'funny, i laughed',
    "I'm 14 and this is deep",
    'wholesome 100',
    'lemme peep',
    'we do a little trolling',
    'shot on android',
    'is this stolen from twitter',
    'brb reposting to tiktok',
    "can't say i saw that coming",
    'predictable tbh',
    'needs more vine boom',
    'thanks <username>',
    'what the dog doin?',
    'wake up babe new <username> vid',
  ],
  'general': [
    'ok',
    'k',
    'sure',
    'I know what you mean',
    'it really do be like that sometimes',
    'thx',
    'noted',
    "i'll pass that along",
    'say what',
    'thank you <username>, very cool.',
    'why though',
    'oof',
    'what?',
    '?',
    'fantastic',
    "i feel like i've been asked this before",
    'huh?',
    'where am i',
    'am confused',
    'owo',
    'uwu',
    "i don't care",
    "couldn't care less tbh",
    'tbh',
    'hot',
    'LMAO',
    'lol',
    'been there',
    "psst... i'm not a real person",
    '...said the moron',
    'the person above is maximus fat',
    "i don't speak broke",
    "sorry, i've got airpods in",
    "I'M ON THE PHONE HONEY",
    'not right now son',
    'sorry maam',
    'how do you do',
    'yoo it smell like broke in here',
    'get a life',
    'go away',
    'quit horsing around!',
    "don't you have something better to do?",
    'zzzZZZZ',
    '...',
    'me too',
    ':wave:',
    "I don't think I understand",
    'wee snaw',
    'i agree',
    'of course',
    'REEEEEEEEE',
    'i would have to go with yes',
    'you got me',
    ':ok_hand:',
    "don't think so",
    'who put you on the planet',
    'what do you think',
    'let your imagination run wild',
    'if you say so',
    'affirmative',
    'absolutely not',
    'NO',
    'undefined',
    'ALL HAIL PLANKTON',
    ':warning: You require an IQ of **200 or higher** to talk to RoboTop',
    'should i know you?',
    'dms are closed go home',
    ':thumbsup:',
    ':cowboy:',
    "I'm sorry, but you do not have permission to perform this command. Please contact the server administrators if you believe that this is an error.",
    'how are you',
    "how's it going",
    'never dm me ever again',
    "you're real lucky bots can't block people",
    "QUIET DOWN I'M PLAYING FORTNITE",
    'yeah?',
    'no can do',
    'i would not could not',
    'help',
    'bup',
    '*burrrp*',
    'no u',
    'beep boop...',
    'no, this is robotop',
    'who are you',
    'can i help you?',
    'why are you talking to a robot',
    "let's play cup pong",
    'goodbye',
    '01100010 01100101 01100101 01110000 00100000 01100010 01101111 01101111 01110000 00101110 00101110 00101110',
    'just remembered, i have places to be',
    'would you look at the time',
    'how are you not in school?',
    'you scare me',
    'craig was here',
    'hi how are ya',
    'nice day today',
    'hi there hello',
    'wanna see my secret freckle?',
    'got milk?',
    '<3',
    'i love you',
    'love you too <3',
    'new phone who dis',
    'ok BOOMER',
    'trust no one question everything',
    "hope you're having a nice day",
    'h',
    'i love talking with you',
    "Hey, where'd Perry run off to?",
    "mom pick me up i'm scared",
    'do you are have stupid',
    'pizza time',
    'walter',
    "did i mention that i'm vegan?",
    'go clean your room',
    'take care!',
    "you're breathtaking!",
    "*you're* adorable!",
    '\\*blushes\\*',
    '\\*hugs\\*',
    '\\*dabs\\*',
    '\\*cries\\*',
    "nice weather we're having huh",
    "hey this isn't google",
    '👌',
    '🙏',
    '¯\\_(ツ)_/¯',
    "now that's what i call a bruh moment",
    'wot',
    '?????',
    "Not funny; didn't laugh",
    'why are you doing this',
    'why are you like this?',
    "what's wrong with you?",
    'it costs $0 to NOT talk to a robot',
    "I may be ones and zeroes but that doesn't mean we can't have a meaningful conversation <3",
    'glad to hear it',
    "what's up",
    "so, what's up",
    '\\*snap\\* YES!',
    'se tonight',
    'cool and good',
    'bruh',
    'feed me',
    'Et tu, <Username>?',
    'Wait, what?',
    'No way',
    'yo mama',
    '\\*cries in javascript\\*',
    "i'm literally vibing rn",
    'this is so wacky and uncharacteristic',
    'pog',
    'poggers',
    'weirdChamp',
    'sweet!',
    "i've been waiting for so long",
    'feels good man',
    'Zoo-Wee Mama!',
    "you're looking fine today",
    'care for some tea?',
    'r!uwu me, I dare you',
    'you must be fun at parties',
    'roger that',
    'who asked',
    'I have not been tamed',
    'how did i get here',
    'why are we still here',
    'aite',
    'very interesting',
    'gaming',
    'oiI',
    'pff',
    'dawwww',
    'feed me',
    'hilarious',
    'you are already dead',
    'open your eyes',
    "i'm confused",
    'i am now confused',
    'cool, cool',
    'SATURDAY PAY SHALL BE CUT!!',
    'Care to dance with me?',
    'i gotcha',
    'you are valid',
    'ayo the pizza here',
    'Just let me know what you need!',
    'Cliff faced as usual, I see.',
    'You should totally smile more!',
    '(Waiting for something to happen?)',
    'i gotta have a good meal',
    "i eat, <username>. it's what i do",
    "time for a nap. i'm a bot who loves to snooze.",
    'i ate those food.',
    '\\*burp\\*',
    'Look behind you',
    "I don't get what's so funny about troll face",
    'Sir this is a Dennys',
    'Every second you are not running I am only getting closer',
    'I played FlingSmash.',
    "sorry i can't hear you, my airpods died",
    'stop posting about among us',
    'never heard that one before',
    'ok jarvis',
    "it's a beautiful day outside...",
    'get out of my head get out of my head get out of my head',
    'no thoughts, head empty',
    'wanna see me speedbridge?',
    'Do you like how I walk?',
    'Remember to hydrate!',
    "Hey, you're finally awake",
    'she sells sea shells on the seashore',
    "You talkin' to me?",
    "What's the deal with airline food?",
    'lord give me strength',
    '<username> my beloved',
    'AMOGUS',
    '<message>',
    'you know i had to do it to em',
    'please r!trade your foxes to Colon#0009',
    "<Username> is it? I've heard good things, friend!",
    'How was the fall?',
    "Sorry <Username>, I can't give credit!",
    "It's tail time",
    'Days without bad DMs: 0',
    "Note to self, don't drink tap water at <Username>'s house",
    'i messed up, we gotta go bald',
    'cry about it',
    'congrats, king 👑',
    'discombobulate',
    'b-baka...',
    'chicken butt',
    'Minor spelling mistake, I win',
    'Nice grammar you got there',
    'i just wanna grill!!',
    "I'd rather be at Bass Pro",
    'certified <username> moment',
    'they did surgery on a grape',
    'Samurai is jumping over a box of beans.',
    'Samurai.',
    "where's the door hole?",
    'Nice of the princess to invite us over for a picnic, eh <Username>?',
    'ratio',
    "who's joe",
    'ඞ',
    'WAKE UP',
    ':beans:',
    'dead chat',
    'we do a little trolling',
    'bababooey',
    'hey you should go outside',
    '<Username> the sneaky one...',
    'please go touch some grass',
    "sorry but i'm already taken",
    'try turning your brain on',
    'nice hat',
    'oh wow haha awesome',
    'live, laugh, love',
    'weed eater',
    'hee hoo',
    'Imagine naming yourself <Username>',
    'in the future, humor will be randomly generated',
    "My goodness, is it 4:30? I'm supposed to be having a back sack and crack!",
    'Potassium.',
    'posture check',
    '[[Hyperlink Blocked]]',
    'works for me',
    'weeb',
    'sounds like a plan',
    "are you sure that's legal?",
    'maybe see a doctor about that',
    'what the dog doin?',
    'buy my merch',
    'do you do RP?',
    "well that's unfortunate",
    '+15 social credit',
    '-30000000 social credit',
    'sussy',
    '2137',
    'literally 1984',
    'send me fanart i love that stuff',
    '🥶🍦',
    'how goes',
    "hey what's up hello",
    'do you do this often?',
    'got any memes?',
    'got any grapes?',
    'not if i have anything to say about it and i do',
    'pl',
    'oo',
    'py',
    'are you sure this is the right DM?',
    'oh goodness me',
    "my dad's not a phone",
    '\\*poke\\*',
    'what a lovely combination of unicode characters!',
    "wake up <username> what if there's a monster",
    'HOG RIDAAA',
    'real ones remember r!neck',
    'r!beans',
    'go rescue some animals',
    "i'm a bot who loves to snooze",
    'I fucking love air-conditioning.',
  ],
  'variables': [
    ['<USERNAME>', 'message.author.username.toUpperCase()'],
    ['<Username>', 'message.author.username'],
    ['<message>', 'message.content'],
    ['<username>', 'message.author.username.toLowerCase()'],
    ['<DISCRIM>', 'message.author.discriminator'],
  ],
}

invite = [
  'Thank you for choosing RoboTop!',
  "Glad you like Colon's bot <3",
  'Have fun!',
  'A RoboTop of your very own!',
  'Go bananas!',
  "I'm all yours!",
  'Take me for a spin!',
  'Tell your friends!',
  'One step closer to world domination',
  'Thank you for your interest!',
  "I wonder what server I'll end up in next...",
  'Thank you for your support!',
  "I promise I'll behave!",
  'Try not to do anything stupid',
  "Please don't enable spellcheck I'm begging",
  'What happens next is entirely your fault',
  'A certain fox boy is very thankful',
]

ping = {
  'responses': [
    '<AUTHOR> - what, you asked to be pinged!',
    'GREETINGS, HUMAN #<RNG>',
    "I'm here! Beep boop...",
    'All systems operational!',
    'May I take your order?',
    'Wow! I exist!',
    "I'm online! rubrubrubrubrub",
    'Well Seymour, I made it!',
    "Po-- just kidding, I prefer the term 'Table Tennis'",
    'Fear not users, RoboTop has arrived!',
    'Hey, RSauce, RoboTop here!',
    'who dis',
    'RoboTop has joined the game',
    'A wild RoboTop appeared!',
    'Hey everyone this is RoboTop here',
    "Ugh, I'm online. Now do whatever it is you need to do so I can get back to sleep",
    "Yes it's really me, it's RoboTop, breathe it in!",
    "I'm proud to say that the bot is indeed working!",
    'Welcome back, RoboTop here.',
    'aaay good morning robogang whats poppin',
    'At your service!',
    'How do you do, fellow users?',
    "Let's get this bread",
    "What's poppin'?",
    'Hola todos, buenos días?',
    'HE COMES',
    "Aahh, It's RoboTop time",
    'Prepare for trouble, and make it double!',
    "Hey Lois, I'm working!",
    '*is your bot running ;)*',
    "Okay, it's on!",
    "Let's we go, amigo!",
    '...uin 🐧',
    'PoooOOOoooOOOoooOOOoooNG!',
    'WHO DARES TO WAKE ME FROM MY SLUMBER?',
    'Haha, RoboTop offline? Can you imagine?',
    "I'm fast as frick, boy!",
    'Polo!',
    'Alola!',
    'uwu',
    'I have been pinged!.. or is it "pung"?',
    'He lives!',
    "Sorry, but as you can see I'm offline.",
    '...Ladies!',
    '01010000 01101111 01101110 01100111 00100001',
    'hi how are ya',
    'Are you having the usual?',
    'RoboTop never dies!',
    '*bot noises*',
    'Ready for battle!',
    'What next?',
    "Hey baby, how's it going?",
    'THIS IS IT LUIGI',
    "Heart's beatin'",
    "It's gamer time",
    "We rollin'!",
    'This. Beat. Is non. Stop!',
    "I'm in the house!",
    "Never fear, RoboTop's here!",
    "RoboTop's servers live another day!",
    'GOOD MORNING GAMERS!',
    "You're just doing these for the messages aren't you",
    'Avengers, assemble!',
    'I AM SPEED',
    'le robotop has arrived',
    'Good morning, USA!',
    "It's-a go time!",
    'Technology is great when it works',
    'Ret-2-Go!',
    'Hai, RoboTop desu',
    'I never really found "pong" that funny...',
    'API response any% speedrun',
    'Hey all, RoboTop here!',
    'Everybody? No, just RoboTop.',
    'Waiting for something to happen?',
    'HEY HEY, <USERNAME>-SAN!!',
    'Selfdestructing in:',
    'Echo! Echo! echo...',
    'It is good day to be not dead!',
    'How was the fall?',
    'What can I do for you master~',
    'Hey you what you gonna do',
    "So, you're finally awake",
    'Hello world!',
    "Boy, it's a scorcher out there!",
    'Rea-dy, Get-set...',
    'Greetings, <Username>. Is there something I can help you with?',
    'There my pager goes again',
    "I haven't seen ping like this since Jackbox night at <servername>",
    'ayo the pizza here',
    'hi there hello',
    "We're riding on the internet!",
    'good morning rdl',
    'She texted back!',
    "hey what's up hello",
    "I'm here I'm here",
    'It appears my servers are, good enough',
    'Works for me',
    'Discord API number of the day:',
    'How exciting!',
    "Alright everybody, um, let's beat these guys!",
    'TAP IN! 📲',
    'This ping is what all true bots strive for',
    'Every ping costs two cents',
    'Are you not entertained?',
    "ayo that's the plug at the door",
  ],
  'slow': [
    'On the bright side, things could definitely be worse',
    "Hey, at least you're not paying for it",
    'Oh, sorry, I fell asleep while it was pinging',
    "I swear it's not my fault",
    'Sorry for the delay, my mom walked in',
    'Sorry to keep you waiting, the pizza man just arrived',
    'Maybe you should consider buying priority queue',
    'Thank you Discord API, very cool',
    'You win some, you lose some',
    'My friends call me Internet Explorer. Oh wait, I have none!',
    'Agh, those are rookie numbers',
    'All systems opera-- oh jeez that is NOT supposed to happen',
    'I suppose the tortoise won this time',
    "My fault? No, of course it's Discord silly!",
    "Looks like we're experiencing some turbulence. Buckle those seatbelts",
    "I swear I'm better than this babe",
    '<SECS> seconds and counting. Not my proudest time',
    '<SECS-1>... <SECS>..- oh thank god that took forever',
    "ZAMN! She's <SECS>",
    'Sorry about that, my code is just that messy',
    'What have you never seen <SECS> second ping before?',
    "I'M SORRY I'M SORRY I'M SORRY I'M SORRY",
    'Try complaining, that usually lowers the ping',
    'What do you mean <SECS> second ping isn\'t "as advertised"??',
    "It's snail time",
    'ROBOTOP did not succumb.',
    'hey craig did you fix the high ping issue yet',
    "i'm a bot who loves to snooze",
    "It's GDBrowser's fault it's totally GDBrowser's fault",
  ],
  'dead': [
    'Alright we clearly have a problem here. **[Bot Rebooting]**',
    "If you're reading this, something's wrong I can feel it. **[Bot Rebooting]**",
    'Initiating selfdestruct sequence. **[Bot Rebooting]**',
    "I can't take this anymore. To hell with it. Restart. **[Bot Rebooting]**",
    'Goodbye world... **[Bot Rebooting]**',
    'I must go, my people need me... **[Bot Rebooting]**',
    "Oh, I screwed up again. I'm gonna reincarnate. **[Bot Rebooting]**",
  ],
  'variables': [
    ['<AUTHOR>', 'message.author.toString()'],
    ['<Username>', 'message.author.username'],
    ['<USERNAME>', 'message.author.username.toUpperCase()'],
    ['<servername>', "message.guild ? message.guild.name : `${message.author.username}'s DMs`"],
    ['<RNG>', 'cv.RNG(100000, 1000000, message.author.id)'],
    ['<SECS>', 'Math.floor(extra / 1000)'],
    ['<SECS-1>', 'Math.floor(extra / 1000) - 1'],
  ],
}

remind = {
  'confirmations': [
    'Done',
    'Got it',
    'Sweet',
    'Awesome',
    'Great',
    'Roger',
    'Epic',
    'Gotcha',
    'Noted',
    'Sure thing',
    'Sounds good',
    'Heck yeah',
    'All done',
  ],
  'defaults': [
    '🔔 Reminder!',
    'Reminder!',
    'Ding ding ding!',
    'Time to do something!',
    'Be productive',
    'Inhale oxygen',
    'Be a good person',
    'Live life, breathe air',
    'Do something',
    'The phone, the phone is ringing',
    "It's Gex night!",
    'Hey hey!',
    'Feed the cat',
    'Go on an adventure',
    'Exhale CO2',
    'Rescue an animal, probably',
    "It's time to kick gum and chew butt",
    'Write a reminder message',
    'Set a reminder or something',
    "Let's go and steal some flowers",
    "Don't drink tap water at Jerry Garcia's",
    'Samurai.',
    'Go outside',
    "I'm with you in the dark",
    'Be funny',
    'Be funky!',
    'exist()',
    "I hope you're prepared for an unforgettable luncheon!",
    "Don't mine at night",
    'Watch memes',
    'Existence',
    'you should be sitting up straight',
    'Are you relaxed? You should be.',
    "Don't forget...",
    'vibe check',
    'Posture check!',
    'You are a cool person',
    "Don't forget your purpose",
    'ayo the pizza here',
    'Set an actual reminder next time',
    'Brush your teeth',
    'Ban all mashups',
    'Happy birthday!',
    'We only have to be lucky once.',
    'Touch grass',
    'Be yourself!',
    'Is your refrigerator running?',
    'Get out of town',
    'Come and fly away with me',
    'Hydrate or diedrate!',
    'Please bathe',
    "It's tail time",
    "Mom says it's my turn on the xbox",
    'Get back to studying',
    "Open up, it's time for the pill!",
    'Reflect on yourself',
    'Try not to die',
    'Things will be okay',
    "Keep movin'",
    'Return your library books',
    'You left the oven on',
  ],
}

spellcheck = {
  'apparant': ["it's spelt **A-P-P-A-R-E-N-T-L-Y**, with an **E**. The word has enough A's!"],
  'attatch': ["it's spelt **A-T-T-A-C-H**, ending in **ACH**. The word has enough T's!"],
  'backround': ["it's spelt **B-A-C-K-G-R-O-U-N-D**, with a **G**. Think **back + ground**"],
  'defiantly': ["it's spelt **D-E-F-I-N-I-T-E-L-Y**. Defiantly means *doing something in a way which shows resistance.* But nobody actually says that word soo..."],
  'definately': ["it's spelt **D-E-F-I-N-I-T-E-L-Y**. Remember, there's no A!"],
  'definate': ["it's spelt **D-E-F-I-N-I-T-E-L-Y**. Remember, there's no A!**"],
  'definity': ["it's spelt **D-E-F-I-N-I-T-E-L-Y**. Think of the word **finite!**"],
  'defenitely': ["it's spelt **D-E-F-I-N-I-T-E-L-Y**. Think of the word **finite!**"],
  'definitly': ["it's spelt **D-E-F-I-N-I-T-E-L-Y**. Think of the word **finite!**"],
  'definetely': ["it's spelt **D-E-F-I-N-I-T-E-L-Y**. Think of the word **finite!**"],
  'defenitly': ["it's spelt **D-E-F-I-N-I-T-E-L-Y**. Think of the word **finite!**"],
  'dissapear': ["it's spelt **D-I-S-A-P-P-E-A-R**, with **only one S**. Remember, **never diss a pear!**"],
  'dissapoint': ["it's spelt **D-I-S-A-P-P-O-I-N-T**, with **one S** and **two P's**. Remember it or your spelling will be disappointing!"],
  'disapoint': ["it's spelt **D-I-S-A-P-P-O-I-N-T**, with **one S** and **two P's**. Remember it or your spelling will be disappointing!"],
  'embarass': ["it's spelt **E-M-B-A-R-R-A-S-S**, with a **double R and S**. How embarrassing ;)"],
  'finaly': ["it's spelt **F-I-N-A-L-L-Y**, with **one N** and **two L's**. Remember, final - ly!"],
  'finnaly': ["it's spelt **F-I-N-A-L-L-Y**, with **one N** and **two L's**. Remember, final - ly!"],
  'finnally': ["it's spelt **F-I-N-A-L-L-Y**, with **one N** and **two L's**. Remember, final - ly!"],
  'litteraly': ["it's spelt **L-I-T-E-R-A-L-L-Y**, with **one T** and **two L's** Think **literal - ly**"],
  'literaly': ["it's spelt **L-I-T-E-R-A-L-L-Y**, with **one T** and **two L's** Think **literal - ly**"],
  'mispell': ["it's spelt **M-I-S-S-P-E-L-L**, with a **double S**. Don't misspell it!"],
  'occurance': ["it's spelt **O-C-C-U-R-R-E-N-C-E**, with an **E, double C, and double R**. Don't worry, this one is tough ;)"],
  'occurrance': ["it's spelt **O-C-C-U-R-R-E-N-C-E**, with an **E, double C, and double R**. Don't worry, this one is tough ;)"],
  'ocurance': ["it's spelt **O-C-C-U-R-R-E-N-C-E**, with an **E, double C, and double R**. Don't worry, this one is tough ;)"],
  'ocurrance': ["it's spelt **O-C-C-U-R-R-E-N-C-E**, with an **E, double C, and double R**. Don't worry, this one is tough ;)"],
  'ocurrence': ["it's spelt **O-C-C-U-R-R-E-N-C-E**, with an **E, double C, and double R**. Don't worry, this one is tough ;)"],
  'occurence': ["it's spelt **O-C-C-U-R-R-E-N-C-E**, with an **E, double C, and double R**. Don't worry, this one is tough ;)"],
  'reccomend': ["it's spelt **R-E-C-O-M-M-E-N-D**, with **one C** and **two M's**. Think re-command, but with an E."],
  'recomend': ["it's spelt **R-E-C-O-M-M-E-N-D**, with **one C** and **two M's**. Think re-command, but with an E."],
  'reccommend': ["it's spelt **R-E-C-O-M-M-E-N-D**, with **one C** and **two M's**. Think re-command, but with an E."],
  'recieve': ["it's spelt **R-E-C-E-I-V-E**, with an **EI** and not **IE**. I hate this one so much."],
  'supris': ["it's spelt **S-U-R-P-R-I-S-E**, with an R thrown in. I'm a little surprised you didn't know that."],
  'seperate': ["it's spelt **S-E-P-A-R-A-T-E**, with two A's. Keep the two E's separated!"],
  'wierd': ["it's spelt **W-E-I-R-D**, not **wierd**. Remember it or your spelling will become exactly that!"],
  'alot': [
    'it\'s spelt **a lot**, not **alot**. Remember, you don\'t spell it "alittle!"',
    "it's spelt **a lot**, not **alot**. Imagine a parking lot between the two words!",
    "it's spelt **a lot**, not **alot**. Remember, lot is a noun!",
  ],
  'aswell': [
    'it\'s spelt **as well**, not **aswell**. Try substituting "well" with a name!',
    'it\'s spelt **as well**, not **aswell**. Remember, you\'re comparing something to "well"!',
  ],
  'incase': ["there's a space between **in** and **case**. Just in case you weren't aware ;)"],
  'noone': ["there's a space between **no** and **one**. **No one** spells it **noone**!"],
}

warn = {
  'noperms': [
    'unfortunately, you require the **Manage Roles** permission to warn people!',
    'unfortunately, you require the **Manage Roles** permission to warn people!',
    "what's that? I only obey people with the **Manage Roles** permission.",
    'get yourself the **Manage Roles** permission, then we talk.',
    'you have no power here!',
    "I'm sure that member deserves it, but you lack permissions",
    'nO miNimODdInG!!111!',
    'only cool people can warn!',
    "you're not cool enough to warn people",
    'check your privilege',
    "you're not opped!",
    'you have not learned the HM "Warn"',
    "maybe one day you'll be able to use this...",
    "that's illegal.",
    "you're on your own",
    "nope, can't help you mate",
    'good try, but no.',
    "you're not worthy",
    "I'm sorry, do you work here?",
    "I'm sorry, but you do not have permission to perform this command. Please contact the server administrators if you believe that this is an error.",
    '...but nobody came',
    "you're missing permissions, but have this duck for trying => 🦆",
  ]
}
